title: blog Janka Hraška
url: http://jankohrasko2.github.io
description: popis blogu Janka Hraška
email: jankohrasko2@gmail.com

markdown: kramdown
excerpt_separator: "\n\n"

permalink: /archive/:year/:month/:day/:title

timezone: Europe/Bratislava

paginate: 15
paginate_path: "/archive/page:num/"

safe: true
lsi: false
exclude: [.gitignore, CNAME, Dockerfile, README.md]

pages: 
  Blog: '/blog/'
  Archiv: '/archiv/'
  OStranke: '/ostranke/'
  RSS: '/atom.xml	

# Custom 
google_analytics_key: UA-XXXXXXX-X

gems:
 - jekyll-paginate
